# Generated by Django 4.0.3 on 2022-04-01 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('rasm', models.URLField(blank=True)),
                ('yil', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Qoshiqchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('yosh', models.PositiveIntegerField()),
                ('davlat', models.CharField(max_length=30)),
                ('yonalish', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Qoshiq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('yil', models.DateField()),
                ('matn', models.CharField(blank=True, max_length=300)),
                ('davomiylik', models.DurationField(blank=True, default='00:03:30')),
                ('qoshiq', models.URLField(blank=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qoshiqlari', to='music.album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='qoshiqchi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albomlari', to='music.qoshiqchi'),
        ),
    ]
