# Generated by Django 4.0.3 on 2022-04-01 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qoshiq',
            name='davomiylik',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=210)),
        ),
    ]
